<h1 style="color:#d53a49;font-weight:600;">Sentiment Analysis with Hotel Reviews</h1>

> **OBJECTIVE:** Build a hotel recommendation bot using *sentiment analysis* and guest *reviews scores*
>
> This dataset contains 515,000 customer reviews and scoring of 1493 luxury hotels across Europe. Meanwhile, the geographical location of hotels are also provided for further analysis.
>
> The csv file contains 17 fields. The description of each field is as below:

---
- **Hotel_Address:** Address of hotel.
- **Review_Date:** Date when reviewer posted the corresponding review.
- **Average_Score:** Average Score of the hotel, calculated based on the latest comment in the last year.
- **Hotel_Name:** Name of Hotel
- **Reviewer_Nationality:** Nationality of Reviewer
- **Negative_Review:** Negative Review the reviewer gave to the hotel. If the reviewer wrote nothing, then it should be: 'No Negative'
- **Review_Total_Negative_Word_Counts:** Total number of words in the negative review.
- **Positive_Review:** Positive Review the reviewer gave to the hotel. If the reviewer wrote nothing, then it should be: 'No Positive'
- **Review_Total_Positive_Word_Counts:** Total number of words in the positive review.
- **Reviewer_Score:** Score the reviewer has given to the hotel, based on his/her experience. The values range between 2.5 - 10.
- **Total_Number_of_Reviews_Reviewer_Has_Given:** Number of Reviews the reviewers has given in the past.
- **Total_Number_of_Reviews:** Total number of valid reviews the hotel has.
- **Tags:** Tags reviewer gave the hotel.
- **days_since_review:** Duration between the review date and scrape date. Note that older reviews might not be as accurate as newer ones due to changes.
- **Additional_Number_of_Scoring:** There are also some guests who just made a scoring on the service rather than a review. This number indicates how many valid scores without review in there.
- **lat:** Latitude of the hotel
- **lng:** longtitude of the hotel
---

<h3 style="font-weight:600;color:white;background:#d53a49;padding:25px;margin:20;text-align:left;display:fill;border-radius:10px 0 0 10px;text-transform:uppercase;">1 | Data Exploration</h3>

<h4 style="font-weight:600;color:white;background:#d53a49;padding:25px;margin:20;text-align:left;display:fill;border-radius:10px 0 0 10px;text-transform:uppercase;">1.1 | Load the Data</h4>

Load the hotel reviews from **CSV** into a pandas DataFrame.<br/>
We also load **time**, so the start and end times can be used to ascertain the file loading time.<br/>

In [45]:
import pandas as pd
import time

print("Loading data file now, this could take a while depending on file size.")
start = time.time()
df = pd.read_csv("../data/Hotel_Reviews.csv")
end = time.time()
print(f"Loading took {round(end-start,2)} seconds.")

Loading data file now, this could take a while depending on file size.
Loading took 1.99 seconds.

<h4 style="font-weight:600;color:white;background:#d53a49;padding:25px;margin:20;text-align:left;display:fill;border-radius:10px 0 0 10px;text-transform:uppercase;">1.2 | Explore the Data</h4>

In this dataset, the data is already *clean* e.g. there are no characters in other languages that could mess up the algorithm that expects only English characters.

<h4 style="font-weight:600;color:white;background:#d53a49;padding:25px;margin:20;text-align:left;display:fill;border-radius:10px 0 0 10px;text-transform:uppercase;">1.3 | Dataframe Operations</h4>

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">1. Print out the shape of the dataframe (i.e. the number of rows and columns)</span>

In [46]:
print(f"The shape of the data (rows, cols) is {df.shape}")

The shape of the data (rows, cols) is (515738, 17)

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">2. Calculate the frequency count for reviewer nationalities</span>

<span>i. How many distinct values are there for the column`Reviewer_Nationality` and what are they?</span><br/>

Use `value_counts()` which returns a Series that has as **index** the country and as **values** the frequency they occur.

In [47]:
nationality_freq = df["Reviewer_Nationality"].value_counts()
num_of_nationalities = nationality_freq.size
print(f"There are {num_of_nationalities} different nationalities.", end="\n\n")
print(nationality_freq.to_string())

There are 227 different nationalities.

Reviewer_Nationality
United Kingdom                           245246
United States of America                  35437
Australia                                 21686
Ireland                                   14827
United Arab Emirates                      10235
Saudi Arabia                               8951
Netherlands                                8772
Switzerland                                8678
Germany                                    7941
Canada                                     7894
France                                     7296
Israel                                     6610
Italy                                      6114
Belgium                                    6031
Turkey                                     5444
Kuwait                                     4920
Spain                                      4737
Romania                                    4552
Russia                                     3900
South Africa                               3821
India                                      3437
Greece                                     3406
China                                      3400
Sweden                                     3368
New Zealand                                3237
Singapore                                  3091
Hong Kong                                  3013
Poland                                     2891
Qatar                                      2757
Austria                                    2412
Egypt                                      2388
Norway                                     2383
Czech Republic                             2311
Lebanon                                    2261
Hungary                                    2185
Malaysia                                   1883
Thailand                                   1880
Brazil                                     1865
Portugal                                   1839
Finland                                    1829
Denmark                                    1724
Malta                                      1685
Bahrain                                    1592
Indonesia                                  1548
Cyprus                                     1381
Luxembourg                                 1359
Croatia                                    1340
Oman                                       1334
Bulgaria                                   1314
Japan                                      1279
Serbia                                     1124
Ukraine                                    1102
Iran                                       1086
South Korea                                1078
Philippines                                1073
Nigeria                                     977
Iceland                                     933
Taiwan                                      923
Pakistan                                    916
Slovakia                                    903
Jersey                                      863
Slovenia                                    796
Jordan                                      757
Estonia                                     757
Lithuania                                   727
Latvia                                      719
Mexico                                      592
Guernsey                                    543
                                            523
Argentina                                   517
Isle of Man                                 405
Gibraltar                                   380
Chile                                       334
Georgia                                     294
Iraq                                        290
Albania                                     286
Sri Lanka                                   284
Macedonia                                   282
Kazakhstan                                  281
Azerbaijan                                  277
Colombia                                    277
Kenya                                       269
Monaco                                      250
Bosnia and Herzegovina                      246
Morocco                                     229
Mauritius                                   216
Belarus                                     192
Montenegro                                  192
Vietnam                                     187
Puerto Rico                                 180
Trinidad and Tobago                         154
Abkhazia Georgia                            153
Bangladesh                                  151
Ghana                                       145
Armenia                                     134
Panama                                      122
Costa Rica                                  120
Peru                                        118
Macau                                       109
Moldova                                     108
Bermuda                                     103
Brunei                                      100
Algeria                                     100
Uruguay                                      91
Venezuela                                    78
Tunisia                                      76
United States Minor Outlying Islands         74
Kosovo                                       72
Libya                                        72
Namibia                                      67
Andorra                                      64
Angola                                       62
Barbados                                     61
Ecuador                                      61
Tanzania                                     58
Palestinian Territory                        54
Guatemala                                    53
Dominican Republic                           52
Sudan                                        51
Zimbabwe                                     51
Maldives                                     49
Uganda                                       47
Botswana                                     42
Cayman Islands                               42
Jamaica                                      41
Cura ao                                      41
Mongolia                                     39
Zambia                                       37
Mozambique                                   35
Cambodia                                     34
Syria                                        33
Bahamas                                      32
Ethiopia                                     32
Aruba                                        31
Paraguay                                     28
Senegal                                      24
El Salvador                                  24
Honduras                                     22
Seychelles                                   21
Kyrgyzstan                                   21
Liechtenstein                                20
Uzbekistan                                   20
Ivory Coast                                  19
Myanmar                                      18
Bolivia                                      18
U S Virgin Islands                           17
Yemen                                        16
British Virgin Islands                       16
Faroe Islands                                16
Tajikistan                                   16
Nicaragua                                    15
Nepal                                        15
Turks Caicos Islands                         14
Antigua Barbuda                              14
Papua New Guinea                             14
Guam                                         14
Rwanda                                       13
Fiji                                         12
St Maarten                                   11
Suriname                                     11
Dominica                                     11
Malawi                                       10
New Caledonia                                10
Saint Kitts and Nevis                         9
Democratic Republic of the Congo              9
Laos                                          9
Cameroon                                      9
Madagascar                                    8
Vanuatu                                       8
Belize                                        8
Mauritania                                    8
Saint Lucia                                   8
Swaziland                                     8
Afghanistan                                   8
Togo                                          7
Gabon                                         7
Crimea                                        6
Sierra Leone                                  6
Benin                                         6
Bhutan                                        6
Reunion                                       6
Haiti                                         6
Falkland Islands Malvinas                     6
Guyana                                        5
Martinique                                    5
Gambia                                        5
Guadeloupe                                    5
Mali                                          5
Turkmenistan                                  5
East Timor                                    4
Saint Martin                                  4
French Guiana                                 4
Samoa                                         4
Burundi                                       3
Antarctica                                    3
Central Africa Republic                       3
Liberia                                       3
Lesotho                                       3
French Polynesia                              3
Grenada                                       3
Saint Barts                                   3
Congo                                         3
Somalia                                       3
San Marino                                    3
Bonaire St Eustatius and Saba                 3
Equatorial Guinea                             2
Montserrat                                    2
St Pierre and Miquelon                        2
Niger                                         2
Wallis and Futuna                             2
Djibouti                                      2
Kiribati                                      2
Cook Islands                                  2
Eritrea                                       2
Saint Vincent Grenadines                      2
South Sudan                                   2
Cocos K I                                     2
American Samoa                                2
Comoros                                       1
Svalbard Jan Mayen                            1
Vatican City                                  1
Anguilla                                      1
Cape Verde                                    1
Northern Mariana Islands                      1
Tuvalu                                        1
Guinea                                        1
Palau                                         1

<span>ii. What reviewer nationality is the most common in the dataset (print country and number of reviews)</span><br/>
<span>iii. What are the next top-10 most frequently found nationalities, and their frequency count?</span>

In [43]:
top_nation = nationality_freq.index[0].strip()
top_nation_freq = nationality_freq.values[0]
next_ten_nation = nationality_freq[1:11].to_string()
print(f'The highest-frequency reviewer nationality is "{top_nation}" with {top_nation_freq} reviews.')
print(f"The next 10 higher-frequency reviewer nationalities are:\n\n{next_ten_nation}")

The highest-frequency reviewer nationality is "United Kingdom" with 245246 reviews.
The next 10 higher-frequency reviewer nationalities are:

Reviewer_Nationality
United States of America     35437
Australia                    21686
Ireland                      14827
United Arab Emirates         10235
Saudi Arabia                  8951
Netherlands                   8772
Switzerland                   8678
Germany                       7941
Canada                        7894
France                        7296

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">3. What was the most frequently reviewed hotel for each of the top-10 reviewer nationalities</span>

Start with a loop and extract all the rows that match the criteria (a specific nationality) into a new dataframe. Then for each country get the hotel frequency.

In [109]:
for nat in nationality_freq.index[:10]:
    nat_df = df[df["Reviewer_Nationality"] == nat]
    freq = nat_df["Hotel_Name"].value_counts()
    print(f"The most reviewed hotel for {nat.strip()} was {freq.index[0]} with {freq.values[0]} reviews.")

The most reviewed hotel for United Kingdom was Britannia International Hotel Canary Wharf with 3833 reviews.
The most reviewed hotel for United States of America was Hotel Esther a with 423 reviews.
The most reviewed hotel for Australia was Park Plaza Westminster Bridge London with 167 reviews.
The most reviewed hotel for Ireland was Copthorne Tara Hotel London Kensington with 239 reviews.
The most reviewed hotel for United Arab Emirates was Millennium Hotel London Knightsbridge with 129 reviews.
The most reviewed hotel for Saudi Arabia was The Cumberland A Guoman Hotel with 142 reviews.
The most reviewed hotel for Netherlands was Jaz Amsterdam with 97 reviews.
The most reviewed hotel for Switzerland was Hotel Da Vinci with 97 reviews.
The most reviewed hotel for Germany was Hotel Da Vinci with 86 reviews.
The most reviewed hotel for Canada was St James Court A Taj Hotel London with 61 reviews.

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">4. How many reviews are there per hotel in the dataset?</span>

We start by creating a new DataFrame from the old one, with only the required columns. Then, we group the rows by "Hotel_Name", count them and put the result in a new column "Total_Reviews_Found". Finally, get rid of all the duplicated rows.

**IMPORTANT NOTE**: We don't use count() because this is an aggregate function producing one row per hotel. Instead, transform("count") produces the same summary but broadcasts the result back to the original rows.

In [164]:
# fmt:off
hotel_freq_df = df[["Hotel_Name", "Total_Number_of_Reviews"]]
hotel_freq_df["Total_Reviews_Found"] = (
    hotel_freq_df.groupby("Hotel_Name")
                 .transform("count")
)
hotel_freq_df = (
    hotel_freq_df.drop_duplicates(subset=["Hotel_Name"])
                 .sort_values(by="Total_Reviews_Found", ascending=False)
)
display(hotel_freq_df)

,Hotel_Name,Total_Number_of_Reviews,Total_Reviews_Found
63942,Britannia International Hotel Canary Wharf,9086,4789
164259,Strand Palace Hotel,9568,4256
504027,Park Plaza Westminster Bridge London,12158,4169
440985,Copthorne Tara Hotel London Kensington,7105,3578
236055,DoubleTree by Hilton Hotel London Tower of London,7491,3212
...,...,...,...
85168,Boundary Rooms Suites,45,12
485009,Ibis Styles Milano Palmanova,207,12
43688,Mercure Paris Porte d Orleans,110,10
481328,Hotel Wagner,135,10
350451,Hotel Gallitzinberg,173,8

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">5. Calculate an average review score for each hotel</span>

While there is an `Average_Score` column for each hotel in the dataset, we can also calculate an average score - the average of all reviewer scores for each hotel.<br/>
A such, we add a new column to the dataframe with the header `Calc_Average_Score` that contains that calculated average. Print out the columns `Hotel_Name`, `Average_Score`, and `Calc_Average_score`.

In [ ]:
# fmt: off
def get_diff_review_avg(row):
    """
    Takes a row and returns the difference between average score and calculated average score.
    """
    return row["Average_Score"] - row["Calc_Average_Score"]


df["Calc_Average_Score"] = (
    round(df.groupby("Hotel_Name")["Reviewer_Score"]
            .transform("mean"),1)
)

df["Average_Score_Difference"] = df.apply(get_diff_review_avg, axis=1)

review_scores_df = (
    df.drop_duplicates(subset=["Hotel_Name"])
      .sort_values(["Average_Score_Difference"])
)

display(review_scores_df[["Average_Score_Difference", "Average_Score", "Calc_Average_Score", "Hotel_Name"]])

,Average_Score_Difference,Average_Score,Calc_Average_Score,Hotel_Name
495945,-0.8,7.7,8.5,Best Western Hotel Astoria
111027,-0.7,8.8,9.5,Hotel Stendhal Place Vend me Paris MGallery by...
43688,-0.7,7.5,8.2,Mercure Paris Porte d Orleans
178253,-0.7,7.9,8.6,Renaissance Paris Vendome Hotel
71274,-0.5,8.9,9.4,Drawing Hotel
...,...,...,...,...
201776,0.7,7.5,6.8,Mercure Paris Op ra Faubourg Montmartre
22189,0.8,7.1,6.3,Holiday Inn Paris Montparnasse Pasteur
250308,0.9,8.6,7.7,MARQUIS Faubourg St Honor Relais Ch teaux
68936,0.9,6.8,5.9,Villa Eugenie
3813,1.3,7.2,5.9,Kube Hotel Ice Bar

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">6. Calculate and print out how many rows have column `Negative_Review` values of "No Negative"</span>

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">7. Calculate and print out how many rows have column `Positive_Review` values of "No Positive"</span>

<span style="color:#d53a49;text-transform:uppercase;font-weight:600;">8. Calculate and print out how many rows have column `Positive_Review` values of "No Positive" **and** `Negative_Review` values of "No Negative"</span>

In [174]:
start = time.time()
no_negative_reviews = df.apply(lambda x: True if x["Negative_Review"] == "No Negative" else False, axis=1)
print(f"Number of No Negative reviews: {len(no_negative_reviews[no_negative_reviews==True].index)}")

no_positive_reviews = df.apply(lambda x: True if x["Positive_Review"] == "No Positive" else False, axis=1)
print(f"Number of No Positive reviews: {len(no_positive_reviews[no_positive_reviews==True].index)}")

both_no_reviews = df.apply(
    lambda x: True if x["Negative_Review"] == "No Negative" and x["Positive_Review"] == "No Positive" else False,
    axis=1,
)
print(f"Number of both No Negative and No Positive reviews: {len(both_no_reviews[both_no_reviews==True].index)}")

end = time.time()
print(f"Lambdas took {round(end-start,2)} seconds.")

Number of No Negative reviews: 127890
Number of No Positive reviews: 35946
Number of both No Negative and No Positive reviews: 127
Lambdas took 6.78 seconds.

Using lambdas seems to take a long time! Let's try and use `sum` to count the rows:

In [179]:
start = time.time()

no_negative_reviews = sum(df.Negative_Review == "No Negative")
print(f"Number of negative reviews: {no_negative_reviews}")

no_positive_reviews = sum(df.Positive_Review == "No Positive")
print(f"Number of positive reviews: {no_positive_reviews}")

both_no_reviews = sum((df.Negative_Review == "No Negative") & (df.Positive_Review == "No Positive"))
print(f"Number of both No Negative and No Positive reviews: {both_no_reviews}")

end = time.time()
print(f"Sum took {round(end-start,2)} seconds.")

Number of negative reviews: 127890
Number of positive reviews: 35946
Number of both No Negative and No Positive reviews: 127
Sum took 0.28 seconds.

In [180]:
df.Negative_Review == "No Negative"

0         False
1          True
2         False
3         False
4         False
          ...
515733    False
515734    False
515735    False
515736     True
515737    False
Name: Negative_Review, Length: 515738, dtype: bool